### ISSUE TITLE
PA Review: Rich Text Formatting

### ISSUE THREAD

**Issue by jubby2000** [jubby2000/infinotes#10]
- [x] Users can store and retrieve their notes in rich text

I had included the option to hide the RTF until the body field is active, but I think the current aesthetic matches what I have. If you'd like me to pursue it I can look into making this happen as well.

**Comment by s-pangburn** [comment]
Looks good! I would only recommend you style it as close as you can to resemble the way Evernote actually looks.

Here's a really well-done example from someone who was in my cohort (she had lots of previous experience, so don't get discouraged by what you see, I really more mean for you to use this as a reference to learn from): https://github.com/achen118/clever-note
