### ISSUE TITLE
Proposal: Database Schema Feedback

### ISSUE THREAD

**Issue by s-pangburn** [jubby2000/infinotes#3]
- [x] In your `notes` table, "json" is not a SQL data type. Should be string (even if ultimately it will be a JSON string!)
- [x] Table and column names should, ideally, be `backticked`. I'm not going to be super picky about this if you don't like how it looks though.

**Comment by jubby2000** [comment]
Actually realized that about the json this weekend (as I was trying to find the best way to store rich text) just forgot to update that part. Thanks, good eye!
