### ISSUE TITLE
Proposal: State Shape Feedback

### ISSUE THREAD

**Issue by s-pangburn** [jubby2000/infinotes#5]
- [x] Your `session` slice of state should probably include a `currentUser`, just to check if anyone is logged in.

That's all for your proposal! Overall, solid work, just get this feedback addressed and you'll be good to go for tomorrow's kickoff 👍

**Comment by jubby2000** [comment]
I actually thought the id referred to the current user, but perhaps that's just the... Session id?

**Comment by s-pangburn** [comment]
Yeah, you should be able to grab the user's username at a moment's notice, no SQL queries necessary 🙂
